0:Transponder 0:20:TeamName:
1:Transponder 1:20:TeamName:
2:Transponder 2:20:TeamName:
3:Transponder 3:20:TeamName:
4:Transponder 4:20:TeamName:
5:Transponder 5:20:TeamName:
6:Transponder 6:20:TeamName:
7:Noisy Cricket:20:Goblin Mode:
8:Bot:20:TeamName:
9:Bot:20:TeamName:
10:Odin:20:RTEAM:
11:Mech99:20:RTEAM:
12:GS Marauder:20:RTEAM:
13:Bot:20:TeamName:
14:Nomad:20:RTEAM:
15:Apophis:20:RTEAM:
16:Domino:20:RTEAM:
17:Numa2:20:Numa:
18:Immortal:20:Cire:
19:OpenMech:20:Chickensaurs:
20:Dictatorial Boss:20:BHNKC:
21:BigHeadGor:20:BHNKC:
22:Domineering CEO:20:HKUST:
23:BigHeadTim:20:HKUST:
24:Tyrannical President:20:HKUST:
25:Uzma:20:TeamName:
26:Bot:20:TeamName:
27:Bot:20:TeamName:
28:Bot:20:TeamName:
29:Bot:20:TeamName:
30:Bot:20:TeamName:
31:Bot:20:TeamName:
32:Bot:20:TeamName:
33:Bot:20:TeamName:
34:Bot:20:TeamName:
35:Bot:20:TeamName:
36:Bot:20:TeamName:
37:Bot:20:TeamName:
38:Bot:20:TeamName:
39:Bot:20:TeamName:
40:Bot:20:TeamName:
41:Bot:20:TeamName:
42:Bot:20:TeamName:
43:Bot:20:TeamName:
44:Bot:20:TeamName:
45:Bot:20:TeamName:
46:Bot:20:TeamName:
47:Bot:20:TeamName:
48:Bot:20:TeamName:
49:Bot:20:TeamName:
50:Bot:20:TeamName:
51:Bot:20:TeamName:
52:Bot:20:TeamName:
53:Bot:20:TeamName:
54:Bot:20:TeamName:
55:Bot:20:TeamName:
56:Bot:20:TeamName:
57:Bot:20:TeamName:
58:Bot:20:TeamName:
59:Bot:20:TeamName:
60:Bot:20:TeamName:
61:Bot:20:TeamName:
62:Bot:20:TeamName:
63:Bot:20:TeamName: